fix(release): do not fail changelog generation for the first tag (#9)

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -34,8 +34,8 @@ jobs:
 
       - name: Generate changelog
         run: |
-          previous=$(git describe --tags --abbrev=0 ${{ inputs.version }}~1)
-          git log --format="* %h %s" $previous..${{ inputs.version }} | tee changelog.txt
+          previous=$(git describe --tags --abbrev=0 ${{ inputs.version }}~1 2> /dev/null) || true # it's ok to fail if this is the first tag.
+          git log --format="* %h %s" ${previous:+^$previous} ${{ inputs.version }} | tee changelog.txt
           echo changelog.txt >> .git/info/exclude # GoReleaser doesn't tolerate git in a dirty state.
 
       - name: Create release
